#DataSource
spring:
  profiles: deploy

  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

  datasource:
    url: jdbc:mysql://localhost:3306/cat?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClass: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  #    config-location: classpath:mybatis/mybatis-config.xml
  #    mapper-locations: classpath:mybatis/mapper/*.xml
#mybatis:
#  type-aliases-package: cn.zq.exam.domain          #mybatis开启实体类别名
#  mapper-locations: classpath:mapper/*.xml   #扫描mapper所在包
